spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: app-ratelimiter
  banner:
    location: classpath:/templates/banner.txt

  cloud:
    config:
      uri: http://localhost:8888
      profile: dev  # ou 'prod', conforme necessário
      #label: main
      fail-fast: true # Opcional, para falhar rapidamente se não conseguir se conectar ao Config Server
#      client:
#        poll-interval: 10000 # Verifica a cada 30 segundos


#  retry:
#    instances:
#      compra-fornecedor:
#        wait-duration: 2s
#        max-attempts: '3'
#        enable-exponential-backoff: 'true'


